// <auto-generated />
using System;
using CBF_API_Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CBF_API_Core.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CBF_API_Core.Model.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataEvento");

                    b.Property<string>("DetalheEvento")
                        .HasMaxLength(300);

                    b.Property<Guid>("PartidaId");

                    b.Property<int>("TipoEvento");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("CBF_API_Core.Model.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<Guid>("TimeId");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("CBF_API_Core.Model.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataPartida");

                    b.Property<int>("GolsTimeMandante");

                    b.Property<int>("GolsTimeVisitante");

                    b.Property<Guid>("Time_MandanteId");

                    b.Property<Guid>("Time_VisitanteId");

                    b.Property<Guid>("TorneioId");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("CBF_API_Core.Model.Time", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.HasKey("Id");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("CBF_API_Core.Model.Torneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("TorneioDataFim");

                    b.Property<DateTime>("TorneioDataInicio");

                    b.HasKey("Id");

                    b.ToTable("Torneios");
                });

            modelBuilder.Entity("CBF_API_Core.Model.Transferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataTransferencia");

                    b.Property<Guid>("JogadorTransferidoId");

                    b.Property<Guid>("TimeDeDestinoId");

                    b.Property<Guid>("TimeDeOrigemId");

                    b.Property<decimal>("ValorTransferencia");

                    b.HasKey("Id");

                    b.ToTable("Transferencias");
                });

            modelBuilder.Entity("CBF_API_Core.Model.Jogador", b =>
                {
                    b.HasOne("CBF_API_Core.Model.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
